Use nixpkgs 22.05 for scripts (#1632)
This should daily updates which are failing with:

```
error: unrecognised flag '--accept-flake-config'
```

See https://buildkite.com/input-output-hk/haskell-dot-nix-nightly-updates/builds/1318#0182f20e-bd2b-4840-a930-af2815df793c

This change also updates to the newer mkdocs in nixpkgs 22.05 and updates the check-path-support to use a combination of nixpkgs and ghc that should be in the hydra cache.