Fix test-only failure for ghcjs (#2180)
* Fix test-only failure for ghcjs

The new `default-setup-ghcjs` has a longer name than `default-setup` and that causes the word `do` to wrap onto the next line.

The expected error now looks like this for ghcjs:

```
Error: default-setup-ghcjs: No executables and no library found. Nothing to
do.
```