Use nixpkgs 22.05 for scripts
This should daily updates which are failing with:

```
error: unrecognised flag '--accept-flake-config'
```

See https://buildkite.com/input-output-hk/haskell-dot-nix-nightly-updates/builds/1318#0182f20e-bd2b-4840-a930-af2815df793c